db:
  image: mysql
  ports:
    - '3306'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
web:
  build: .
  links:
    - db
  volumes:
    - ./courses:/home/app/webapp/courses
    - ./db-data:/var/lib/mysql
